from rapsodie.playlist_maker.auto_playlists.AutoPlaylist import AutoPlaylist
from rapsodie.playlist_maker.auto_playlists.Diggers import Diggers
from rapsodie.playlist_maker.auto_playlists.RandomTracks import RandomTracks
